import { Check, CircleHelp, Clock3, Film, Heart, Utensils, Wifi, X } from 'lucide-react-native';
import { useLocalSearchParams } from 'expo-router';
import React from 'react';
import QRCode from 'react-native-qrcode-svg';
import { ActivityIndicator, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Card, PrimaryButton } from '../../components/ui';
import { useClaimGuestMealOption, useGuestInvitation, useGuestMealOptions, useGuestMealRequests, useGuestMoviePolls, useRespondGuestInvitation, useSubmitGuestMealRequest, useVoteGuestMoviePoll } from '../../lib/queries';
import type { MealType } from '../../lib/types';
import { radius, type as t, useTheme } from '../../lib/theme';

function first(value: string | string[] | undefined) { return Array.isArray(value) ? value[0] : value; }

function dateTime(value: string) {
  return new Intl.DateTimeFormat('zh-CN', { month: 'long', day: 'numeric', weekday: 'long', hour: '2-digit', minute: '2-digit', hour12: false }).format(new Date(value));
}

const mealLabels: Record<MealType, string> = { breakfast: '早餐', lunch: '午餐', dinner: '晚餐' };
const mealRequestStatus = { pending: '等待家庭确认', accepted: '已接受', rejected: '暂不安排' };

function dateLabel(value: string) {
  return new Intl.DateTimeFormat('zh-CN', { month: 'numeric', day: 'numeric', weekday: 'short' }).format(new Date(`${value}T00:00:00`));
}

function GuestMoviePolls({ token }: { token: string | undefined }) {
  const c = useTheme();
  const polls = useGuestMoviePolls(token);
  const vote = useVoteGuestMoviePoll(token);
  const [choices, setChoices] = React.useState<Record<string, string[]>>({});
  if (polls.isLoading || polls.isError || !polls.data?.length) return null;
  const toggle = (pollId: string, optionId: string, maxChoices: number, single: boolean) => {
    setChoices((current) => {
      const selected = current[pollId] ?? polls.data?.find((poll) => poll.id === pollId)?.selectedOptionIds ?? [];
      if (single) return { ...current, [pollId]: selected.includes(optionId) ? [] : [optionId] };
      if (selected.includes(optionId)) return { ...current, [pollId]: selected.filter((id) => id !== optionId) };
      if (selected.length >= maxChoices) return current;
      return { ...current, [pollId]: [...selected, optionId] };
    });
  };
  return <View style={styles.pollList}>{polls.data.map((poll) => {
    const selected = choices[poll.id] ?? poll.selectedOptionIds;
    return <Card key={poll.id} style={styles.pollCard}><View style={styles.pollTitle}><Film color={c.tint} size={20} /><View style={{ flex: 1 }}><Text style={[t.headline, { color: c.label }]}>{poll.title}</Text><Text style={[t.caption, { color: c.secondaryLabel, marginTop: 2 }]}>{poll.totalVoters} 人已参与{poll.closesAt ? ` · 截止 ${dateTime(poll.closesAt)}` : ''}</Text></View></View>{poll.description ? <Text style={[t.footnote, { color: c.secondaryLabel, marginTop: 10 }]}>{poll.description}</Text> : null}<View style={styles.pollOptions}>{poll.options.map((option) => { const checked = selected.includes(option.id); return <Pressable key={option.id} accessibilityRole="checkbox" accessibilityState={{ checked }} onPress={() => toggle(poll.id, option.id, poll.maxChoices, poll.voteMode === 'single')} style={[styles.pollOption, { borderColor: checked ? c.tint : c.separator, backgroundColor: checked ? c.tintSoft : c.fill }]}><View style={{ flex: 1, minWidth: 0 }}><Text style={[t.subhead, { color: c.label }]}>{option.media?.title ?? option.label}{option.media?.year ? ` (${option.media.year})` : ''}</Text>{option.description ? <Text style={[t.caption, { color: c.secondaryLabel, marginTop: 2 }]}>{option.description}</Text> : null}</View><Text style={[t.caption, { color: c.secondaryLabel }]}>{option.voteCount} 票</Text>{checked ? <Check color={c.tint} size={17} /> : null}</Pressable>; })}</View><PrimaryButton title={selected.length ? '提交观影选择' : '清空我的选择'} onPress={() => void vote.mutate({ pollId: poll.id, optionIds: selected })} loading={vote.isPending} style={{ marginTop: 12 }} />{vote.isError ? <Text style={[t.caption, { color: c.red, marginTop: 8 }]}>{vote.error instanceof Error ? vote.error.message : '提交失败，请稍后重试'}</Text> : null}</Card>;
  })}</View>;
}

function GuestMealMenu({ token }: { token: string | undefined }) {
  const c = useTheme();
  const options = useGuestMealOptions(token);
  const claim = useClaimGuestMealOption(token);
  if (options.isLoading) return null;
  if (!options.data?.length) return <Card style={styles.mealMenuCard}><View style={styles.pollTitle}><View style={[styles.mealMark, { backgroundColor: c.orangeSoft }]}><Utensils color={c.orange} size={19} /></View><View style={{ flex: 1 }}><Text style={[t.headline, { color: c.label }]}>本次来访菜单</Text><Text style={[t.footnote, { color: c.secondaryLabel, marginTop: 3 }]}>家庭还没有安排可选菜品，稍后可以再打开链接查看。</Text></View></View></Card>;
  return <Card style={styles.mealMenuCard}><View style={styles.pollTitle}><View style={[styles.mealMark, { backgroundColor: c.orangeSoft }]}><Utensils color={c.orange} size={19} /></View><View style={{ flex: 1 }}><Text style={[t.headline, { color: c.label }]}>本次来访菜单</Text><Text style={[t.caption, { color: c.secondaryLabel, marginTop: 2 }]}>选择想吃的菜后，家庭会看到你的选择。</Text></View></View><View style={styles.menuGroups}>{options.data.map((menu) => <View key={menu.id} style={styles.menuGroup}><Text style={[t.footnote, { color: c.secondaryLabel }]}>{dateLabel(menu.mealDate)} · {mealLabels[menu.mealType]}</Text>{menu.items.map((item) => <View key={item.id} style={[styles.menuOption, { backgroundColor: item.request?.status === 'accepted' ? c.greenSoft : item.request?.status === 'rejected' ? c.orangeSoft : c.fill }]}><View style={{ flex: 1, minWidth: 0 }}><Text style={[t.subhead, { color: c.label }]}>{item.dishName}</Text><Text style={[t.caption, { color: c.secondaryLabel, marginTop: 2 }]}>{item.dishCategory}</Text></View>{item.request ? <Text style={[t.caption, { color: item.request.status === 'accepted' ? c.green : item.request.status === 'rejected' ? c.orange : c.tint }]}>{mealRequestStatus[item.request.status]}</Text> : <Pressable accessibilityRole="button" accessibilityLabel={`选择${item.dishName}`} onPress={() => void claim.mutate(item.id)} disabled={claim.isPending} style={[styles.menuClaim, { backgroundColor: c.tintSoft }]}><Text style={[t.caption, { color: c.tint, fontWeight: '700' }]}>我要这道</Text></Pressable>}</View>)}</View>)}</View>{claim.isError ? <Text style={[t.caption, { color: c.red, marginTop: 9 }]}>{claim.error instanceof Error ? claim.error.message : '提交失败，请稍后重试'}</Text> : null}</Card>;
}

function GuestMealRequests({ token, dates }: { token: string | undefined; dates: string[] }) {
  const c = useTheme();
  const requests = useGuestMealRequests(token);
  const submit = useSubmitGuestMealRequest(token);
  const [mealDate, setMealDate] = React.useState('');
  const [mealType, setMealType] = React.useState<MealType>('dinner');
  const [dishName, setDishName] = React.useState('');
  const [note, setNote] = React.useState('');
  React.useEffect(() => { if (!mealDate && dates[0]) setMealDate(dates[0]); }, [dates, mealDate]);
  const current = requests.data?.find((request) => request.mealDate === mealDate && request.mealType === mealType);
  React.useEffect(() => { setDishName(current?.dishName ?? ''); setNote(current?.note ?? ''); }, [current?.id, mealDate, mealType]);
  if (!dates.length || requests.isLoading) return null;
  const editable = !current || current.status === 'pending';
  return <Card style={styles.mealRequestCard}><View style={styles.pollTitle}><View style={[styles.mealMark, { backgroundColor: c.orangeSoft }]}><Utensils color={c.orange} size={19} /></View><View style={{ flex: 1 }}><Text style={[t.headline, { color: c.label }]}>菜单外请求</Text><Text style={[t.caption, { color: c.secondaryLabel, marginTop: 2 }]}>菜单没有的菜，可以在这里提出。</Text></View></View><View style={styles.slotChoices}>{dates.map((value) => <Pressable key={value} accessibilityRole="button" onPress={() => setMealDate(value)} style={[styles.slotChoice, { borderColor: mealDate === value ? c.tint : c.separator, backgroundColor: mealDate === value ? c.tintSoft : c.fill }]}><Text style={[t.caption, { color: mealDate === value ? c.tint : c.secondaryLabel }]}>{dateLabel(value)}</Text></Pressable>)}</View><View style={styles.slotChoices}>{(Object.keys(mealLabels) as MealType[]).map((value) => <Pressable key={value} accessibilityRole="button" onPress={() => setMealType(value)} style={[styles.slotChoice, { borderColor: mealType === value ? c.tint : c.separator, backgroundColor: mealType === value ? c.tintSoft : c.fill }]}><Text style={[t.caption, { color: mealType === value ? c.tint : c.secondaryLabel }]}>{mealLabels[value]}</Text></Pressable>)}</View>{editable ? <><TextInput value={dishName} onChangeText={setDishName} placeholder="想吃什么菜？" placeholderTextColor={c.tertiaryLabel} maxLength={120} style={[styles.requestInput, { color: c.label, backgroundColor: c.fill }]} /><TextInput value={note} onChangeText={setNote} placeholder="口味、忌口或其他备注（可选）" placeholderTextColor={c.tertiaryLabel} maxLength={300} multiline style={[styles.requestNote, { color: c.label, backgroundColor: c.fill }]} /><PrimaryButton title={current ? '更新点菜请求' : '提交点菜请求'} onPress={() => void submit.mutate({ mealDate, mealType, dishName, note: note || null })} loading={submit.isPending} style={{ marginTop: 12 }} /></> : <View style={[styles.requestResult, { backgroundColor: current.status === 'accepted' ? c.greenSoft : c.orangeSoft }]}><Text style={[t.headline, { color: current.status === 'accepted' ? c.green : c.orange }]}>{mealRequestStatus[current.status]}</Text><Text style={[t.footnote, { color: c.secondaryLabel, marginTop: 3 }]}>{current.dishName}{current.reviewNote ? ` · ${current.reviewNote}` : ''}</Text></View>}{submit.isError ? <Text style={[t.caption, { color: c.red, marginTop: 8 }]}>{submit.error instanceof Error ? submit.error.message : '提交失败，请稍后重试'}</Text> : null}<View style={styles.requestHistory}>{(requests.data ?? []).filter((request) => request.id !== current?.id).map((request) => <View key={request.id} style={styles.historyRow}><Text style={[t.caption, { color: c.secondaryLabel, flex: 1 }]}>{dateLabel(request.mealDate)} · {mealLabels[request.mealType]} · {request.dishName}</Text><Text style={[t.caption, { color: request.status === 'accepted' ? c.green : request.status === 'rejected' ? c.orange : c.tint }]}>{mealRequestStatus[request.status]}</Text></View>)}</View></Card>;
}

export default function GuestInvitationScreen() {
  const c = useTheme();
  const token = first(useLocalSearchParams<{ token?: string | string[] }>().token);
  const invitation = useGuestInvitation(token);
  const respond = useRespondGuestInvitation(token);
  if (invitation.isLoading) return <SafeAreaView style={[styles.screen, { backgroundColor: c.bg }]}><ActivityIndicator color={c.tint} style={{ marginTop: 120 }} /></SafeAreaView>;
  if (invitation.isError || !invitation.data) return <SafeAreaView style={[styles.screen, { backgroundColor: c.bg }]}><View style={styles.center}><CircleHelp color={c.orange} size={34} /><Text style={[t.title2, { color: c.label, marginTop: 14 }]}>邀请链接不可用</Text><Text style={[t.subhead, { color: c.secondaryLabel, textAlign: 'center', marginTop: 6 }]}>它可能已过期、被撤销，或对应来访已取消。</Text></View></SafeAreaView>;
  const data = invitation.data;
  const responded = data.response.attending !== null;
  return <SafeAreaView style={[styles.screen, { backgroundColor: c.bg }]}><ScrollView contentContainerStyle={styles.content}><View style={[styles.mark, { backgroundColor: c.tintSoft }]}><Heart color={c.tint} size={26} /></View><Text style={[t.title1, { color: c.label, textAlign: 'center', marginTop: 14 }]}>你好，{data.guest.name}</Text><Text style={[t.subhead, { color: c.secondaryLabel, textAlign: 'center', marginTop: 5 }]}>{data.householdName} 邀请你参加一次来访</Text><Card style={styles.card}><Text style={[t.title2, { color: c.label }]}>{data.visit.title}</Text><View style={styles.meta}><Clock3 color={c.secondaryLabel} size={17} /><Text style={[t.subhead, { color: c.secondaryLabel, flex: 1 }]}>{dateTime(data.visit.startsAt)}{data.visit.endsAt ? ` 至 ${dateTime(data.visit.endsAt)}` : ''}</Text></View>{data.visit.note ? <Text style={[t.subhead, { color: c.secondaryLabel, marginTop: 13 }]}>{data.visit.note}</Text> : null}</Card>{data.wifi ? <Card style={styles.wifiCard}><View style={styles.wifiTitle}><Wifi color={c.blue} size={20} /><View style={{ flex: 1 }}><Text style={[t.headline, { color: c.label }]}>访客 Wi-Fi</Text><Text style={[t.footnote, { color: c.secondaryLabel, marginTop: 2 }]}>{data.wifi.ssid}</Text></View></View><View style={styles.qr}><QRCode value={data.wifi.qrPayload} size={188} color="#111827" backgroundColor="#ffffff" /></View><Text style={[t.caption, { color: c.secondaryLabel, textAlign: 'center', marginTop: 11 }]}>用手机相机或系统 Wi-Fi 扫描即可连接</Text></Card> : null}{data.capabilities.mealRequests ? <><GuestMealMenu token={token} /><GuestMealRequests token={token} dates={data.mealRequestDates} /></> : null}{data.capabilities.movieVoting ? <GuestMoviePolls token={token} /> : null}{responded ? <View style={[styles.response, { backgroundColor: data.response.attending ? c.greenSoft : c.orangeSoft }]}>{data.response.attending ? <Check color={c.green} size={21} /> : <X color={c.orange} size={21} />}<View style={{ flex: 1 }}><Text style={[t.headline, { color: data.response.attending ? c.green : c.orange }]}>{data.response.attending ? '已确认参加' : '已告知无法参加'}</Text><Text style={[t.footnote, { color: c.secondaryLabel, marginTop: 3 }]}>需要变更时，请联系接待你的家庭成员。</Text></View></View> : <View style={styles.actions}><PrimaryButton title="我会参加" onPress={() => void respond.mutate(true)} loading={respond.isPending} icon={<Check color="#fff" size={18} />} /><Pressable accessibilityRole="button" disabled={respond.isPending} onPress={() => void respond.mutate(false)} style={[styles.decline, { backgroundColor: c.fill }]}><Text style={[t.headline, { color: c.label }]}>这次无法参加</Text></Pressable>{respond.isError ? <Text style={[t.footnote, { color: c.red, textAlign: 'center' }]}>{respond.error instanceof Error ? respond.error.message : '提交失败，请稍后重试'}</Text> : null}</View>}<Text style={[t.caption, { color: c.tertiaryLabel, textAlign: 'center', marginTop: 20 }]}>此页面只显示本次来访明确授权的内容。</Text></ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({ screen: { flex: 1 }, content: { width: '100%', maxWidth: 560, alignSelf: 'center', padding: 24, paddingTop: 62, paddingBottom: 42 }, mark: { width: 56, height: 56, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center', alignSelf: 'center' }, card: { marginTop: 26, padding: 18 }, meta: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, marginTop: 13 }, wifiCard: { marginTop: 14, padding: 18 }, wifiTitle: { flexDirection: 'row', alignItems: 'center', gap: 9 }, qr: { alignSelf: 'center', padding: 12, marginTop: 16, backgroundColor: '#fff', borderRadius: radius.sm }, pollList: { gap: 12, marginTop: 14 }, pollCard: { padding: 16 }, pollTitle: { flexDirection: 'row', alignItems: 'flex-start', gap: 8 }, pollOptions: { gap: 8, marginTop: 13 }, pollOption: { minHeight: 52, borderWidth: 1, borderRadius: radius.sm, padding: 10, flexDirection: 'row', alignItems: 'center', gap: 8 }, mealMenuCard: { marginTop: 14, padding: 16 }, menuGroups: { gap: 12, marginTop: 13 }, menuGroup: { gap: 7 }, menuOption: { minHeight: 54, borderRadius: radius.sm, padding: 10, flexDirection: 'row', alignItems: 'center', gap: 8 }, menuClaim: { minHeight: 30, borderRadius: radius.sm, paddingHorizontal: 9, alignItems: 'center', justifyContent: 'center' }, mealRequestCard: { marginTop: 14, padding: 16 }, mealMark: { width: 34, height: 34, borderRadius: radius.sm, alignItems: 'center', justifyContent: 'center' }, slotChoices: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginTop: 12 }, slotChoice: { minHeight: 34, borderWidth: 1, borderRadius: radius.sm, paddingHorizontal: 10, alignItems: 'center', justifyContent: 'center' }, requestInput: { minHeight: 44, borderRadius: radius.sm, paddingHorizontal: 11, marginTop: 12 }, requestNote: { minHeight: 68, borderRadius: radius.sm, paddingHorizontal: 11, paddingTop: 10, marginTop: 8, textAlignVertical: 'top' }, requestResult: { borderRadius: radius.sm, padding: 12, marginTop: 12 }, requestHistory: { gap: 6, marginTop: 12 }, historyRow: { flexDirection: 'row', gap: 8, alignItems: 'center' }, actions: { gap: 10, marginTop: 18 }, decline: { minHeight: 48, borderRadius: radius.sm, alignItems: 'center', justifyContent: 'center' }, response: { marginTop: 18, borderRadius: radius.md, padding: 15, flexDirection: 'row', gap: 10, alignItems: 'center' }, center: { padding: 28, alignItems: 'center', marginTop: 80 } });
