FROM node:22-alpine AS build

RUN npm install --global pnpm@10.34.5

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/api/package.json ./apps/api/package.json

RUN pnpm install --frozen-lockfile --filter api...

COPY apps/api ./apps/api

RUN pnpm --filter api build

FROM node:22-alpine AS production-dependencies

RUN npm install --global pnpm@10.34.5

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/api/package.json ./apps/api/package.json

RUN pnpm install --prod --frozen-lockfile --filter api...

FROM node:22-alpine AS runtime

ENV NODE_ENV=production

WORKDIR /app/apps/api

COPY --chown=node:node --from=production-dependencies /app/node_modules /app/node_modules
COPY --chown=node:node --from=production-dependencies /app/apps/api/node_modules ./node_modules
COPY --chown=node:node --from=production-dependencies /app/apps/api/package.json ./package.json
COPY --chown=node:node --from=build /app/apps/api/dist ./dist

RUN mkdir -p uploads && chown node:node uploads

USER node

EXPOSE 3100

CMD ["node", "dist/main.js"]
