// 已迁移到 packages/contracts 的域：类型从契约包导入再 re-export，本文件不再手工维护它们
import type {
  ActivityModule,
  AppNotification,
  CalendarEntry,
  CalendarEvent,
  Dish,
  DishCategory,
  DishIngredient,
  DishRecipeStep,
  DishRecipeVariant,
  DishRecipeVariantIngredient,
  DishRecipeVariantLink,
  DishRecipeVariantStep,
  DishReferenceLink,
  DishSkillLevel,
  Ingredient,
  InventoryActionResult,
  InventoryBatch,
  InventoryBatchStatus,
  InventoryCategory,
  InventoryItem,
  InventoryTransaction,
  InventoryTransactionType,
  MemberDishSkill,
  MenuInventoryPreview,
  RecipeDish,
  ShoppingInventoryPreview,
  ShoppingItem,
  HouseholdPoll,
  HouseholdReminder,
  HouseholdTask,
  PointsAccount,
  PointsLedger,
  PointsLedgerType,
  PollCategory,
  PollOptionResult,
  PollStatus,
  PollVoteMode,
  ReminderRecipient,
  AgentRuntimeKind,
  AgentPageEntityType,
  AgentPageContext,
  AgentRunStatus,
  AgentRuntimeHealth,
  AgentStatus,
  AgentSettings,
  AgentRoutineKind,
  AgentRoutine,
  AgentResponseStyle,
  AgentMemberProfile,
  AgentMemoryScope,
  AgentMemoryKind,
  AgentMemoryStatus,
  AgentMemoryConfidenceSource,
  AgentMemoryKey,
  AgentMemoryItem,
  CreateAgentMemoryCandidateDto,
  AgentMemoryForgetResult,
  AgentMemoryClearResult,
  AgentRun,
  AgentConversation,
  AgentMessage,
  AgentToolPresentationItem,
  AgentToolPresentation,
  AgentToolEvent,
  AgentProposalStatus,
  AgentActionProposal,
  AgentProposalGroupStatus,
  AgentProposalGroupStep,
  AgentProposalGroupEvent,
  AgentProposalGroup,
  AgentConversationDetail,
  AgentChannelPairingStatus,
  AgentMemberChannel,
  AgentChannelPairing,
  CreatedAgentChannelPairing,
  MediaType,
  MediaMetadataSource,
  MediaMetadataExternalProvider,
  MediaSourceSearchStatus,
  HouseholdMediaStatus,
  MediaExternalRef,
  MediaSearchResult,
  MediaSearchResponse,
  MediaSourceConfig,
  MediaTitle,
  HouseholdMedia,
  MediaConnectorKind,
  MediaConnectorState,
  MediaConnectorSummary,
  MediaConnectorSettings,
  MediaPlaybackUserDirectory,
  MoviePilotWebhookResult,
  PlaybackWebhookResult,
  ViewingSessionStatus,
  ViewingSession,
  ViewingProgress,
  MediaLibraryMatch,
  MediaLibraryAvailability,
  MediaLibraryItem,
  MediaLibraryResponse,
  MediaLibrarySyncResponse,
  MediaRequestStatus,
  MediaRequest,
  BackupScheduleFrequency,
  BackupCapacityStatus,
  BackupRunKind,
  BackupRunStatus,
  BackupPolicy,
  BackupRun,
  BackupDashboard,
  KnowledgeArticleCategory,
  KnowledgeRevisionChangeType,
  KnowledgeArticle,
  KnowledgeArticleRevision,
  FamilyMemoryCategory,
  FamilyMemorySourceModule,
  FamilyMemoryPhoto,
  FamilyMemory,
  AssetCategory,
  AssetRenewalIntervalMonths,
  AssetStatus,
  AssetDocumentType,
  AssetDocument,
  MaintenancePlan,
  MaintenanceConsumable,
  MaintenanceConsumableSnapshot,
  MaintenanceRecord,
  HomeAsset,
  MaintenanceCompletionResult,
  MaintenanceConsumablesPreview,
  MaintenanceShoppingResult,
  Guest,
  VisitStatus,
  GuestWifiSecurity,
  GuestMealRequestStatus,
  GuestWifiProfile,
  GuestInvitation,
  CreatedGuestInvitation,
  Visit,
  GuestInvitationPreview,
  GuestMealRequest,
  GuestMealOption,
  GuestMoviePoll,
  TravelPlanStatus,
  TravelChecklistStatus,
  TravelChecklistCategory,
  TravelChecklistItem,
  TravelPlan,
  TravelTemplateItem,
  TravelPackingTemplate,
  ReminderSource,
  ReminderSourceModule,
  ReminderStatus,
  Reward,
  RewardRedemption,
  RewardRedemptionStatus,
  TaskInstanceStatus,
  TaskOccurrence,
  TaskRecurrence,
  DishRecipeSnapshot,
  HouseholdActivity,
  MealType,
  Menu,
  MenuDateCount,
  MenuEvent,
  MenuEventType,
  MenuItem,
  MenuItemStatus,
  NotificationChannel,
  NotificationChannelKind,
  NotificationChannelPreference,
  NotificationDelivery,
  NotificationDeliveryAttempt,
  NotificationDeliveryStatus,
  NotificationModule,
  AccountProfile,
  CreatedHouseholdInvitation,
  FinanceAccount,
  FinanceAccountType,
  FinanceBudget,
  FinanceCategory,
  FinanceCategoryKind,
  FinancePosting,
  FinanceSummary,
  FinanceTransaction,
  FinanceTransactionType,
  HouseholdInvitation,
  InvitationPreview,
  ManagedMember,
  Member,
  MemberRole,
  AuthSetupStatus,
  SmartMenuCandidate,
  SmartMenuPlan,
} from '@family/contracts';

// 菜品 / 菜谱 / 购物 / 库存域类型已迁到 packages/contracts
export type {
  Dish,
  DishCategory,
  DishIngredient,
  DishRecipeStep,
  DishRecipeVariant,
  DishRecipeVariantIngredient,
  DishRecipeVariantLink,
  DishRecipeVariantStep,
  DishReferenceLink,
  DishSkillLevel,
  Ingredient,
  InventoryActionResult,
  InventoryBatch,
  InventoryBatchStatus,
  InventoryCategory,
  InventoryItem,
  InventoryTransaction,
  InventoryTransactionType,
  MemberDishSkill,
  MenuInventoryPreview,
  RecipeDish,
  ShoppingInventoryPreview,
  ShoppingItem,
};

// 菜单 / 通知 / 活动域类型已迁到 packages/contracts
export type {
  ActivityModule,
  AppNotification,
  DishRecipeSnapshot,
  HouseholdActivity,
  MealType,
  Menu,
  MenuDateCount,
  MenuEvent,
  MenuEventType,
  MenuItem,
  MenuItemStatus,
  NotificationChannel,
  NotificationChannelKind,
  NotificationChannelPreference,
  NotificationDelivery,
  NotificationDeliveryAttempt,
  NotificationDeliveryStatus,
  NotificationModule,
};

// 账号 / 财务 / 智能菜单域类型已迁到 packages/contracts
export type {
  AccountProfile,
  CreatedHouseholdInvitation,
  FinanceAccount,
  FinanceAccountType,
  FinanceBudget,
  FinanceCategory,
  FinanceCategoryKind,
  FinancePosting,
  FinanceSummary,
  FinanceTransaction,
  FinanceTransactionType,
  HouseholdInvitation,
  InvitationPreview,
  ManagedMember,
  SmartMenuCandidate,
  SmartMenuPlan,
};

// 出行域类型已迁到 packages/contracts
export type {
  TravelPlanStatus,
  TravelChecklistStatus,
  TravelChecklistCategory,
  TravelChecklistItem,
  TravelPlan,
  TravelTemplateItem,
  TravelPackingTemplate,
};

// 备份运维 / 知识库 / 家庭回忆 域类型已迁到 packages/contracts
export type {
  BackupScheduleFrequency,
  BackupCapacityStatus,
  BackupRunKind,
  BackupRunStatus,
  BackupPolicy,
  BackupRun,
  BackupDashboard,
  KnowledgeArticleCategory,
  KnowledgeRevisionChangeType,
  KnowledgeArticle,
  KnowledgeArticleRevision,
  FamilyMemoryCategory,
  FamilyMemorySourceModule,
  FamilyMemoryPhoto,
  FamilyMemory,
};

// 成员与账号初始化状态同样来自 packages/contracts
export type { Member, MemberRole, AuthSetupStatus };

// 资产维护域类型已迁到 packages/contracts
export type {
  AssetCategory,
  AssetRenewalIntervalMonths,
  AssetStatus,
  AssetDocumentType,
  AssetDocument,
  MaintenancePlan,
  MaintenanceConsumable,
  MaintenanceConsumableSnapshot,
  MaintenanceRecord,
  HomeAsset,
  MaintenanceCompletionResult,
  MaintenanceConsumablesPreview,
  MaintenanceShoppingResult,
};

// 观影与媒体域类型已迁到 packages/contracts
export type {
  MediaType,
  MediaMetadataSource,
  MediaMetadataExternalProvider,
  MediaSourceSearchStatus,
  HouseholdMediaStatus,
  MediaExternalRef,
  MediaSearchResult,
  MediaSearchResponse,
  MediaSourceConfig,
  MediaTitle,
  HouseholdMedia,
  MediaConnectorKind,
  MediaConnectorState,
  MediaConnectorSummary,
  MediaConnectorSettings,
  MediaPlaybackUserDirectory,
  MoviePilotWebhookResult,
  PlaybackWebhookResult,
  ViewingSessionStatus,
  ViewingSession,
  ViewingProgress,
  MediaLibraryMatch,
  MediaLibraryAvailability,
  MediaLibraryItem,
  MediaLibraryResponse,
  MediaLibrarySyncResponse,
  MediaRequestStatus,
  MediaRequest,
};

// 日历域类型已迁到 packages/contracts
export type { CalendarEntry, CalendarEvent };

// 访客域类型已迁到 packages/contracts
export type {
  Guest,
  VisitStatus,
  GuestWifiSecurity,
  GuestMealRequestStatus,
  GuestWifiProfile,
  GuestInvitation,
  CreatedGuestInvitation,
  Visit,
  GuestInvitationPreview,
  GuestMealRequest,
  GuestMealOption,
  GuestMoviePoll,
};

// 任务域类型已迁到 packages/contracts（Zod schema 推导），这里只做 re-export
export type {
  HouseholdTask,
  TaskInstanceStatus,
  TaskOccurrence,
  TaskRecurrence,
};

// 积分与奖励域类型已迁到 packages/contracts
export type {
  PointsAccount,
  PointsLedger,
  PointsLedgerType,
  Reward,
  RewardRedemption,
  RewardRedemptionStatus,
};

// 投票域类型已迁到 packages/contracts（Zod schema 推导），这里只做 re-export
export type {
  HouseholdPoll,
  PollCategory,
  PollOptionResult,
  PollStatus,
  PollVoteMode,
};

// 提醒域类型已迁到 packages/contracts
export type {
  HouseholdReminder,
  ReminderRecipient,
  ReminderSource,
  ReminderSourceModule,
  ReminderStatus,
};

// 小管家智能体域类型已迁到 packages/contracts
export type {
  AgentRuntimeKind,
  AgentPageEntityType,
  AgentPageContext,
  AgentRunStatus,
  AgentRuntimeHealth,
  AgentStatus,
  AgentSettings,
  AgentRoutineKind,
  AgentRoutine,
  AgentResponseStyle,
  AgentMemberProfile,
  AgentMemoryScope,
  AgentMemoryKind,
  AgentMemoryStatus,
  AgentMemoryConfidenceSource,
  AgentMemoryKey,
  AgentMemoryItem,
  CreateAgentMemoryCandidateDto,
  AgentMemoryForgetResult,
  AgentMemoryClearResult,
  AgentRun,
  AgentConversation,
  AgentMessage,
  AgentToolPresentationItem,
  AgentToolPresentation,
  AgentToolEvent,
  AgentProposalStatus,
  AgentActionProposal,
  AgentProposalGroupStatus,
  AgentProposalGroupStep,
  AgentProposalGroupEvent,
  AgentProposalGroup,
  AgentConversationDetail,
  AgentChannelPairingStatus,
  AgentMemberChannel,
  AgentChannelPairing,
  CreatedAgentChannelPairing,
};
